### PR TITLE
Feature/encode

### PR DESCRIPTION
**Pull request by 777moneymaker**
# Changes

- First of all, encoding works XD For each property set as 'true' in config, encoding does the following:
    * Checks the range of possible value for property
    * Computes a new range that doesn't overlap with new ranges for other properties
    * If there is a joker, then value of each property (marked as 'true') is encoded into one of 10 UTF-8 character for it's respective range and this property is added to the joker. Example: "joker!^*LH"
- Added more informations to logs, especially when some useful situations might occur. Example: protein not found
- Moved argparse arguments to config
    - number changed to "enumerate"
    - all of previous arguments from ['number', 'collapse', 'consecutive'] and new params are now in config under name 'sequential'. Example in repo in config. Possible value for 'sequential' are ['none', 'enumerate', 'collapse', 'consecutive', 'encode']. User must specify one
- Added some info to JSON schema and implemented better validation in `main()`
- Default config is used when no config is supplied
- If config is supplied and protein props are not supplied, then validator checks if 'sequential' in config is not set to 'encode'. If it is, then parser panics because program cant encode any properties without props file.
- generally added more printing various communicates to the user
## NOTE:
By default we are scaling ranges of possible values to remap them onto ascii table. But with outliers, we're mapping values outside of our computed ranges. So I came up with an idea that we start mapping to ascii char no. 34 (\"). Then we can mark the outliers as ascii char no.33 "!". 

# Some examples
### Example output
```bash
python parsers/pajtonparser/pajtonparser.py Data/phrog/ Data/gff
/ -o result --config tadpole_config.json --props prot_props.json
Config... |████████████████████████████████████████| (!) 1 in 0.1s (9.84/s)
Props... |████████████████████████████████████████| (!) 1 in 4.8s (0.21/s)
PHROGs... |████████████████████████████████████████| 18760/18760 [100%] in 3.0s (6168.66/s)
on 5: Computed range for property 'molecular_weight': '(250.31520000000003, 81127.66300000022)'
on 6: Computed range for property 'aromaticity': '(0.0, 0.24528301886792453)'
on 7: Computed range for property 'instability_index': '(-53.933802816901434, 90.80882352941175)'
on 8: Computed range for property 'gravy': '(-3.4032258064516143, 0.9900000000000002)'
on 9: Computed range for property 'isoelectric_point': '(4.0500284194946286, 11.999967765808105)'
on 10: Computed new range for property 'molecular_weight': '(34, 43)'
on 11: Computed new range for property 'aromaticity': '(44, 53)'
on 12: Computed new range for property 'instability_index': '(54, 63)'
on 13: Computed new range for property 'gravy': '(64, 73)'
on 14: Computed new range for property 'isoelectric_point': '(74, 83)'
Props... |████████████████████████████████████████| 15/15 [100%] in 4.8s (3.13/s)
GFFs... |████████████████████████████████████████| 18760/18760 [100%] in 16.4s (1147.07/s)
Sentences... |████████████████████████████████████████| 1683469/1683469 [100%] in 1.9s (880223.33/s)

Done processing all files.
```
### Example result
```
["phrog_32689", "joker\".=DQ", "joker\",;FI", "joker!.;IL", "joker$.;DO", "joker\".;FO", "joker\"0;ER", "joker\".:DK", "phrog_572",
"joker#.:GK", "joker#.:EP", "joker#.;EN", "joker#.;EN", "phrog_1933", "joker\"-9FK", "joker\",<EQ", "joker$-;EJ", "joker\"-:EJ",
 "joker\",:EI", "joker\"0<EJ", "joker\",;FO", "joker\".;FO", "joker%.<EO", "joker\"/:CQ", "joker\"/<DL", "joker\".;FL", "joker!,9IK", 
"phrog_478", "joker\"/:GL", "joker\".:FJ"]
```
### Example log
```
on 18760: 21:07:44,551 POND-PONDLOG INFO Processed all available phrog files
21:07:44,553 POND-PONDLOG DEBUG Started producing ranges for protein params
on 15: 21:07:50,86 POND-PONDLOG DEBUG Successfully produced all ranges
on 337: 21:07:50,401 POND-PONDLOG ERROR Protein 'Q079884|1' not found
21:09:34,331 MAIN-PONDLOG CRITICAL Config's 'sequential' prop is set to 'encode' but protein props not supplied
```

# EDIT !!!
After applying changes that @orloj  proposed (in comments) here is updated output:
```
[["!.<EL00008", "!0<FL01516", "!-;FK01717", "!0;FP00001"], ["!/<FP00003", "!/;FN01083", "!/<FP00904", "!.=EM01655", "!/;FO01654", "!0;HP01270", "!.;FM01463", "!1<EK00121", "!.<FP#####", "!-<EL01605", "!/<FK00069", "!-;FK01666", "!0;FK01669", "!/;FK00112", "!0!FK01548", "!/;FM01618", "!/<FL00017", "!0<FO00067", "!0<FK00256", "!0=FQ00093", "!/<FM00062", "!0<HK01803", "!0<EP00036", "!/<FK00309", "!0;FN00038", "!/;GK07214"], ["!1;FK03505"]}
```

Format (encoding)(phrog number formatted to have exactly 5 chars ||  "#####" in case of joker)

### CODE REVIEW

**Review by phenolophthaleinum — APPROVED** [review]
hopefully good

**Review by orloj — CHANGES_REQUESTED** [review]
Great work! But there are some key details missing:
- both jokers and phrogs should use the new encoding
- phrogs need to keep their respective number (we need to decode them during evaluation)
- all words after the encoding should have the same length

examples:
[properties][phrog number]
phrog1 = \",;FO00001
phrog100 = \"0<EJ00100
joker = \"/:GL#####

**Comment by AvirFrog** [comment]
Now looks good, but i agree with @orloj about missing key details

**Review by AvirFrog — CHANGES_REQUESTED** [review]
Now looks good, but I agree with @orloj about missing key details

**Comment by 777moneymaker** [comment]
@orloj  @AvirFrog  Check now.

**Review by orloj — APPROVED** [review]
All of my previous comments have been addressed

**Review by phenolophthaleinum — CHANGES_REQUESTED** [review]
misses unnotated proteins, hence no lookup table (coded: decoded) can be created for later steps in training

**Comment by 777moneymaker** [comment]
> misses unnotated proteins, hence no lookup table (coded: decoded) can be created for later steps in training

I Think thats fixed by using "!!!!!#####" for unannotated

**Review by AvirFrog — APPROVED** [review]
For me it's Ok  👍🏻  

Merry Christmas! 🎄 🎅🏻

**Pull request merged**
